export default [
  {
    // 경기도시공사 프로젝트
    id: "gicoapart",
    pics: require("../../assets/images/folio/gicoapart.png"),
    name: "GICO Housing Subscription Center",
    age: `2017.12 ~ 2018.04`,
    distance: "Complete",
    position: "Backend & FrontEnd Spring & Jquery",
    titleDetail:
      "경기도시공사 인터넷청약시스템 구축 프로젝트(2017.12 ~2018.04)",
    subDescriptions: [
      "경기도 및 경기도시공사에서 성공적으로 진행중인 따복하우스 사업을 인터넷시스템으로 구축",
      "전자정부프레임워크, Tibero, ibatis, jQuery,Netfunnel,Dguard",
      "12월 중순 1차 인터넷 청약신청시스템 선 구축 후 운영 및 실시간 데이터를 통한",
      "경쟁률 및 현황 분석을 제공 및 민원사항 수렴 후 빠른 조치 제공",
      "분석단계 SH/LH 컨설팅 및 선진사례도출 > RFP, 제안서 기반 요구사항 / 추적표 / 과업대비표 / 도메인정의 도출 > 설계단계",
      "유즈케이스 / 화면UI설계서 자료 도출",
      "UI설계서를 위한 Nexacro를 사용한 화면 설계",
    ],
  },
  {
    // 오산백년대학 프로젝트
    id: "osan",
    pics: require("../../assets/images/folio/osan.png"),
    name: "Osan Citizen Univ Web",
    age: "2017.04 ~ 2018.04",
    distance: "Complete",
    position: "Backend & FrontEnd Spring & Jquery",
    titleDetail:
      "오산시 공공기관 오산백년 시민대학 시스템 구축 프로젝트(2017.04~2018.01)",
    subDescriptions: [
      "분석 단계 - 요구사항 도출 및 화면 설계",
      "설계 단계 - 화면 설계를 통한 자료 사전 및 도메인 정의, ERD작성",
      "학습 플랫폼(물음표 학교, 느낌표 학교) 개발",
      "나눔 플랫폼(재능기부) 개발",
      "강사 관리 시스템 개발",
      "통합 예약시스템(징검다리교실) 개발",
      "시멘틱(의미 기반) 검색/분석 시스템 구축(Konan Search 솔루션 사용)",
      "사용자 권한 별 관리 기능 제공",
      "클라이언트 접속 지연시간 튜닝(무거워진 메인/상세 페이지 소스/라이브러리 관리)",
      "관리자 시스템 개발(배너, 게시물 관리, 사업관리, 권한 관리, 통계, 접속 로그, 회원관리, 예약관리, 공통코드관리",
      "플랫폼 중심의 강사, 활동가, 수강생 간의 연계 네트워크 구성)",
      "형상 관리(SVN), 젠킨스(Maven빌드 tomcat war redeploy)",
      "리포팅 툴을 통한 관리자 통합 분석 및 보고서 제공(ClipReport)",
      "웹표준/웹접근성 관리",
    ],
  },
  {
    // 키즈랜드
    id: "kidsland",
    pics: require("../../assets/images/folio/kidsland.png"),
    name: "KT IPTV Middle Ware KidsLand Service v2",
    age: "2018.05 ~ 2019.09",
    distance: "Complete",
    position: "FrontEnd Javascript",
    titleDetail: "알티캐스트 & KT 셋탑 키즈랜드 2.0 프로젝트 (2018.05~2018.10)",
    subDescriptions: [
      "알티캐스트 & KT IPTV ACAP 미들웨어 어플리케이션 개발",
      "셋탑 어플리케이션 모듈 키즈랜드2.0 프로젝트",
      "전체적인 UI 변경 및 voiceable 로직 추가",
      "QA테스트를 통한 이슈사항 관리 및 송출 전 안정화",
      "관련 기사 https://www.mk.co.kr/news/special-edition/view/2018/12/777042/",
    ],
  },
  {
    id: "beeapp",
    pics: require("../../assets/images/folio/beeapp.png"),
    name: "National Institute of Agricultural Sciences App",
    age: "2020.03 ~ 2020.06",
    distance: "Complete",
    position: "FrontEnd React",
    titleDetail: "국립농원과학원 봉군형성실 Mobile App 개발(2020.03 ~ 2020.06)",
    subDescriptions: [
      "국립 농과원 web project 기반 React Native로 App 개발 진행",
      "Flask / mysql 로 개발된 서버의 API 를 가지고 클라이언트 개발",
      " ReactNative / NativeBase / Victory Chart 로 개발",
    ],
  },
  {
    id: "beeweb",
    pics: require("../../assets/images/folio/beeweb.png"),
    name: "National Institute of Agricultural Sciences Web",
    age: "2020.01 ~ Now",
    distance: "Progress",
    position: "FrontEnd ReactNative",
    titleDetail: "국립농원과학원 봉군형성실 Web Console 개발( 2020.01 ~ 현재 )",
    subDescriptions: [
      "국립농업과학원 봉군형성실 iot Project의 web console 개발진행",
      "Flask / mysql 로 개발된 서버의 API 를 가지고 클라이언트 개발",
      "React / Material-UI로 개발.",
      "실시간 데이터 fetching 처리 및 Data Visualization 개발",
    ],
  },
  {
    id: "telematices",
    pics: require("../../assets/images/folio/tele.png"),
    name: "Telematics Web App Service Project",
    age: `2019.12 ~ Now`,
    distance: "Progress",
    position: "FrontEnd React",
    titleDetail: "Gint Connect Telematics 플랫폼 개발 (2019.12 ~ 현재)",
    subDescriptions: [
      "Gint-Connect 단말기로 쌓여진 트랙터 데이터를 이용한 Web Admin 어플리케이션 개발",
      "AWS lambda / Aws DynamoDB를 이용해 개발된 API 기준",
      "React SPA Application 개발환경 부터 S3 Bucket Product 환경까지 구성 및 개발 진행",
      "React / Amplify / Ant design / styled-components 등 사용",
      "AppSync(GraphQL) 을 통한 Subscription 기반 소켓통신 및 실시간 알림 및 실시간 데이터 변경 처리",
      "AppSync VTL 코드 작성",
      "Mobx를 이용한 상태 관리 및 비즈니스 로직 분산 개발. ApexChart를 이용한 통계 관련 Data Visualization",
      "GitLab CI / CD 를 통한 Docker Container build test / e2e test / Deploy PipeLine 작성 및 자동화 구성",
      "AWS S3 / CloudFront를 이용한 프로덕션 빌드 결과물 배포",
      "Cypress를 이용한 e2e test code 작성 및 테스트 자동화",
      "디자이너의 와이어프레임을 참고하여 StoryBook 으로 UX / UI 문서화 진행.",
      "서비스 기획 회의 및 요구사항도출 문서화",
    ],
  },
];
